version: '3.4'

services:
  backend-flask:
    image: zk15xyz/cruddur-backend:latest
    build:
      context: backend-flask/
      dockerfile: Dockerfile
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEN_URL=${BACKEND_URL}
    ports:
      - 4567:4567
    depends_on:
      - dynamodb-local
      - db

  frontend-react-js:
    image: zk15xyz/cruddur-frontend:latest
    build:
      context: frontend-react-js/
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    ports:
      - 3000:3000
    volumes:
      - ./frontend-react-js:/frontend-react-js
    depends_on:
      - backend-flask
  dynamodb-local:
    # https://stackoverflow.com/questions/67533058/persist-local-dynamodb-data-in-volumes-lack-permission-unable-to-open-databa
    # We needed to add user:root to get this working.
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

networks: 
  internal-network:
    driver: bridge
    name: cruddur
volumes:
  db:
    driver: local